In [1]:
print('Hello World!')

Hello World!

In [3]:
import seaborn as sns

df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [15]:
missing_values = df.isnull().sum()

print("Missing Values: " + str(missing_values))

Missing Values: survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [ ]:
df ['age'] = df['age'].fillna(df['age'].median())
df.head()

# df['deck'].dtype

# df['deck'] = df['deck'].fillna('Unknown')
df.dropna(subset=['deck'], inplace=True)
df.dropna(subset=['embarked'], inplace=True)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.duplicated().any()
df = df.drop_duplicates()

False

In [ ]:
df['sex'].unique()

['female' 'male']

In [26]:

Q1 = df['age'].quantile(0.25)
Q3 = df['age'].quantile(0.75)
IQR = Q3 - Q1 

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

age_outliers = df[(df['age'] < lower) | df['age'] > upper]

print(age_outliers)

Empty DataFrame
Columns: [survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone]
Index: []

In [ ]:

Q1 = df['fare'].quantile(0.25)
Q3 = df['fare'].quantile(0.75)
IQR = Q3 - Q1 

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
fare_outliers = df[(df['fare'] < lower) | df['fare'] > upper]

print(fare_outliers)

Empty DataFrame
Columns: [survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone]
Index: []

In [30]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

df['embarked'] = label_encoder.fit_transform(df['embarked'])

print(df[['embarked']].head())

    embarked
1          0
3          2
6          2
10         2
11         2

In [41]:
import pandas as pd

df_date = pd.DataFrame(
    ['2023-07-10', '2026-09-03', '2022-07-20', '2025-10-10', '2020-09-11'],
    columns=['ticket_purchase_date']
)

df_date['ticket_purchase_date'] = pd.to_datetime(df_date['ticket_purchase_date'])

df_date['purchase_year'] = df_date['ticket_purchase_date'].dt.year
df_date['purchase_month'] = df_date['ticket_purchase_date'].dt.month

df_date.head()

  ticket_purchase_date  purchase_year  purchase_month
0           2023-07-10           2023               7
1           2026-09-03           2026               9
2           2022-07-20           2022               7
3           2025-10-10           2025              10
4           2020-09-11           2020               9

In [43]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,0,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,2,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,2,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,2,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,2,First,woman,False,C,Southampton,yes,True

In [ ]:
df['name'] = df['name'].str.lower()

df['name'] = (
    df['name']
    .str.replace(r"\b(mr|mrs|miss)\b","",regex=True)
    .str.strip()
)

KeyError: 'name'

In [46]:
bins = [0, 12, 19, 64, 100]
labels = ['child', 'teen', 'adult', 'senior']

df['age_groups'] = pd.cut(
    df['age'],
    bins = bins,
    labels = labels
)

print(df[['age', 'age_groups']].head())

     age age_groups
1   38.0      adult
3   35.0      adult
6   54.0      adult
10   4.0      child
11  58.0      adult

In [47]:
#Function practice

def sayHello():
    print('Hello!')


sayHello()

Hello!

In [52]:
def sayHelloTo(name):
    print('Hello', name)

sayHelloTo(('Jimmy'))

Hello Jimmy

In [ ]:
def addition(a,b):
    '''Takes two values, returns sum of values'''
    sayHello()
    return a+b

addition(1,4)

Hello!

5

In [70]:
def removeDupesAndNulls(df):
    df = df.dropna()
    df = df.drop_duplicates()
    return df

In [ ]:
def removeOutliers(df):
    mask = pd.Series(True, index=df.index)
    numericalColumns = df.select_dtypes(include='number')
    for column in numericalColumns:
        Q1 = df[f'{column}'].quantile(0.25)
        Q3 = df[f'{column}'].quantile(0.75)
        IQR = Q3 - Q1 

        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        mask &= df[column].between(lower, upper)

    clean_df = df[mask]
    outliers_df = df[~mask]

    return clean_df, outliers_df

In [65]:
df_titanic = sns.load_dataset("titanic")

In [71]:
removeDupesAndNulls(df_titanic)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [72]:
clean_df, outliers_df = removeOutliers(df_titanic)

In [73]:
clean_df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True

In [74]:
outliers_df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False